name: Deploy Flask App

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python -m pytest

    - name: Build Docker Image
      run: docker build -t ai-devops-app .

    - name: (Optional) Push to DockerHub / ECR
      run: echo "Image Built Successfully"
